server:
  port: 7085

spring:
  application:
    name: eureka-user-3

  redis:
    password: 123456
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 2000

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:7080/eureka
  instance:
    prefer-ip-address: true

#客户端负载均衡模式为 随机模式
#EUREKA-CLIENT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


