server:
  port: 9080

spring:
  application:
    name: spring_boot_quartz
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.147.99:3306/lang?useUnicode=true&characterEncoding=UTF-8&useSSL=no
    username: root
    password: q1w2e3r4LXH!

eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://localhost:7080/eureka
