server:
  port: 7091

spring:
  application:
    name: eureka-client-feign


eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://localhost:7080/eureka
zuul:
#  ignored-services: '*'
  routes:
    zuul-client:
      path: /client/**
      serviceId: eureka-client


