server:
  port: 7086

spring:
  application:
    name: eureka-client-feign

eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://localhost:7080/eureka
feign:
  hystrix:
    enabled: true

# Feign日志记录仅响应级别
logging.level.project.user.UserClient: DEBUG
