server:
  port: 7082

spring:
  application:
    name: eureka-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.147.99:3306/lang?useUnicode=true&characterEncoding=UTF-8&useSSL=no
    username: root
    password: q1w2e3r4LXH!

  redis:
    password: 123456
    database: 0
    host: 106.13.191.132
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 2000

eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://localhost:7080/eureka
  instance:
    prefer-ip-address: true
