server:
  port: 8082

spring:
  application:
    name: cloud-config-client
  # 分布式配置中心
  cloud:
    config:
      label: master
#      profile: dev
      uri: http://localhost:8888/

eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://localhost:7080/eureka
