server:
  port: 7090

spring:
  application:
    name: eureka-client-feign-with-hystrix-factory


eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://localhost:7080/eureka
feign:
  hystrix:
    enabled: true
