server:
  port: 7080
#spring:
#  security:
#    user:
#      name: haohao
#      password: 123456
spring:
  application:
    name: eureka-server

  redis:
    password: 123456
    database: 0
    host: 39.105.147.99
    port: 6379

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:7080/eureka


memcache:
  server: 39.105.147.99:11211
  failover: true
  initConn: 100
  minConn: 20
  maxConn: 1000
  maintSleep: 50
  nagel: false
  socketTO: 3000
  aliveCheck: true