server:
  port: 7080
#spring:
#  security:
#    user:
#      name: haohao
#      password: 123456
spring:
  application:
    name: eureka-server

  redis:
    password: 123456
    timeout: 5000
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 106.13.191.132:7001
        - 106.13.191.132:7002
        - 106.13.191.132:7003
        - 106.13.191.132:7004
        - 106.13.191.132:7005
        - 106.13.191.132:7006
      lettuce:
        pool:
          max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
          max-idle: 10 # 连接池中的最大空闲连接
          min-idle: 5 # 连接池中的最小空闲连接
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:7080/eureka



