server:
  port: 7080
#spring:
#  security:
#    user:
#      name: haohao
#      password: 123456
spring:
  application:
    name: eureka-server

  redis:
    password: 123456
    database: 0
    host: 106.13.191.132
    port: 6379

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:7080/eureka



